export const FETCH_PLANET_REQUEST = "FETCH_PLANET_REQUEST";
export const FETCH_PLANET_SUCCESS = "FETCH_PLANET_SUCCESS";

export const FETCH_PLANET_LIST_REQUEST = "FETCH_PLANET_LIST_REQUEST";
export const FETCH_PLANET_LIST_SUCCESS = "FETCH_PLANET_LIST_SUCCESS";
